// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrF88_xETjT3MeS75OxRzW4A3z6WP2No8',
    appId: '1:40290821564:web:a29f2c3d7de2789e5bf7b9',
    messagingSenderId: '40290821564',
    projectId: 'facebooksingin-78842',
    authDomain: 'facebooksingin-78842.firebaseapp.com',
    databaseURL: 'https://facebooksingin-78842-default-rtdb.firebaseio.com',
    storageBucket: 'facebooksingin-78842.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzglnPcPW3jKcWauYhmP_-vOaGRRgXakA',
    appId: '1:40290821564:android:33a68ad29c3890b15bf7b9',
    messagingSenderId: '40290821564',
    projectId: 'facebooksingin-78842',
    databaseURL: 'https://facebooksingin-78842-default-rtdb.firebaseio.com',
    storageBucket: 'facebooksingin-78842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdMn8XUd0a4CSLl8fax9dye8IOEsf1YG0',
    appId: '1:40290821564:ios:b5a9331a93be80115bf7b9',
    messagingSenderId: '40290821564',
    projectId: 'facebooksingin-78842',
    databaseURL: 'https://facebooksingin-78842-default-rtdb.firebaseio.com',
    storageBucket: 'facebooksingin-78842.appspot.com',
    iosClientId: '40290821564-oe89u9tusq65nesghj7rpk28jhgk92v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.component',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdMn8XUd0a4CSLl8fax9dye8IOEsf1YG0',
    appId: '1:40290821564:ios:f2c4dc9a3860b9e95bf7b9',
    messagingSenderId: '40290821564',
    projectId: 'facebooksingin-78842',
    databaseURL: 'https://facebooksingin-78842-default-rtdb.firebaseio.com',
    storageBucket: 'facebooksingin-78842.appspot.com',
    iosClientId: '40290821564-hgbj5m1r1afpccb0gjhvivu73tn4csp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.component.RunnerTests',
  );
}
